
export enum STATUS {
  INITIALED = 'INITIALED',
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  COMPLETE = 'COMPLETE',
  ERROR = 'ERROR',
  TIMEOUT = 'TIMEOUT',
  CANCELLED = 'CANCELLED',
  PAUSED = 'PAUSED',
  //
  // RETRYING = 'RETRYING',
}